### ISSUE TITLE
[Epic] Creation of an Accounting entry.

### ISSUE THREAD

**Issue by proteusvi** [proteusvi/aglae#5]
# Creation of an Accounting entry.

## Accounting entry.
- [ ]  Creating an Accounting entry.
- [ ] Modifying an Accounting entry.
- [ ] Removing an Accounting entry.
